### ISSUE TITLE
Bug: mermaid not registered

### ISSUE THREAD

**Issue by ShravanSunder** [reworkd/AgentGPT#434]
Sometimes agent gpt will try to generate mermaid diagrams and the page will crash

```
react_devtools_backend.js:2655 Error: Unknown language: `mermaid` is not registered
    at t (938-c7ff48da5abca333.js:45:235291)
    at Object.ew [as highlight] (938-c7ff48da5abca333.js:45:235475)
    at 938-c7ff48da5abca333.js:45:343254
    at 938-c7ff48da5abca333.js:45:406466
    at node (element<code>) (938-c7ff48da5abca333.js:45:405981)
    at node (element<pre>) (938-c7ff48da5abca333.js:45:406169)
    at node (root) (938-c7ff48da5abca333.js:45:406169)
    at i (938-c7ff48da5abca333.js:45:406242)
    at i (938-c7ff48da5abca333.js:45:406420)
    at 938-c7ff48da5abca333.js:45:342677
overrideMethod @ react_devtools_backend.js:2655
a5 @ framework-2bb1844fb22814b3.js:9
a.componentDidCatch.t.callback @ framework-2bb1844fb22814b3.js:9
lH @ framework-2bb1844fb22814b3.js:9
uY @ framework-2bb1844fb22814b3.js:9
e @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9
oI @ framework-2bb1844fb22814b3.js:9
oC @ framework-2bb1844fb22814b3.js:9
r4 @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9
react_devtools_backend.js:2655 Error: Unknown language: `mermaid` is not registered
    at t (938-c7ff48da5abca333.js:45:235291)
    at Object.ew [as highlight] (938-c7ff48da5abca333.js:45:235475)
    at 938-c7ff48da5abca333.js:45:343254
    at 938-c7ff48da5abca333.js:45:406466
    at node (element<code>) (938-c7ff48da5abca333.js:45:405981)
    at node (element<pre>) (938-c7ff48da5abca333.js:45:406169)
    at node (root) (938-c7ff48da5abca333.js:45:406169)
    at i (938-c7ff48da5abca333.js:45:406242)
    at i (938-c7ff48da5abca333.js:45:406420)
    at 938-c7ff48da5abca333.js:45:342677
overrideMethod @ react_devtools_backend.js:2655
K @ main-5cad439296d5027f.js:1
fn @ main-5cad439296d5027f.js:1
componentDidCatch @ main-5cad439296d5027f.js:1
a.componentDidCatch.t.callback @ framework-2bb1844fb22814b3.js:9
lH @ framework-2bb1844fb22814b3.js:9
uY @ framework-2bb1844fb22814b3.js:9
e @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9
oI @ framework-2bb1844fb22814b3.js:9
oC @ framework-2bb1844fb22814b3.js:9
r4 @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9
react_devtools_backend.js:2655 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
overrideMethod @ react_devtools_backend.js:2655
K @ main-5cad439296d5027f.js:1
fn @ main-5cad439296d5027f.js:1
componentDidCatch @ main-5cad439296d5027f.js:1
a.componentDidCatch.t.callback @ framework-2bb1844fb22814b3.js:9
lH @ framework-2bb1844fb22814b3.js:9
uY @ framework-2bb1844fb22814b3.js:9
e @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9
oI @ framework-2bb1844fb22814b3.js:9
oC @ framework-2bb1844fb22814b3.js:9
r4 @ framework-2bb1844fb22814b3.js:9
(anonymous) @ framework-2bb1844fb22814b3.js:9

```

**Comment by asim-shrestha** [comment]
Similar to #352, our highlighter does not support all languages and leads to this error. I've put in a fix, let me know if that works. 

Additionally going to close this in favor of the other ticket
