### ISSUE TITLE
🐛 Issue with Serper running locally 

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/AgentGPT#649]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

The search tool when executed by the Agent should behave properly. 

### Current behaviour

The search tool gets stuck and the following platform errors occur

```
| 2023-05-31 20:57:02.451 | INFO     | logging:callHandlers:1706 - 172.24.0.1:53204 - "POST /api/agent/execute HTTP/1.1" 500
platform  | 2023-05-31 20:57:02.452 | ERROR    | logging:callHandlers:1706 - Exception in ASGI application
platform  | 
platform  | Traceback (most recent call last):
platform  | 
platform  |   File "<string>", line 1, in <module>
platform  |   File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
platform  |     exitcode = _main(fd, parent_sentinel)
platform  |                │     │   └ 4
platform  |                │     └ 7
platform  |                └ <function _main at 0x7fd606bd9a80>
platform  |   File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 133, in _main
platform  |     return self._bootstrap(parent_sentinel)
platform  |            │    │          └ 4
platform  |            │    └ <function BaseProcess._bootstrap at 0x7fd606cab240>
platform  |            └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
platform  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
platform  |     self.run()
platform  |     │    └ <function BaseProcess.run at 0x7fd606caa7a0>
platform  |     └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
platform  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
platform  |     self._target(*self._args, **self._kwargs)
platform  |     │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7fd606bd6290>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
platform  |     │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
platform  |     │    │        │    └ ()
platform  |     │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
platform  |     │    └ <function subprocess_started at 0x7fd60603e160>
platform  |     └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
platform  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
platform  |     target(sockets=sockets)
platform  |     │              └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]
platform  |     └ <bound method Server.run of <uvicorn.server.Server object at 0x7fd605ee5390>>
platform  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
platform  |     return asyncio.run(self.serve(sockets=sockets))
platform  |            │       │   │    │             └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]
platform  |            │       │   │    └ <function Server.serve at 0x7fd60603d260>
platform  |            │       │   └ <uvicorn.server.Server object at 0x7fd605ee5390>
platform  |            │       └ <function run at 0x7fd606328f40>
platform  |            └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
platform  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
platform  |     return runner.run(main)
platform  |            │      │   └ <coroutine object Server.serve at 0x7fd605eece10>
platform  |            │      └ <function Runner.run at 0x7fd6063a07c0>
platform  |            └ <asyncio.runners.Runner object at 0x7fd605ee4d50>
platform  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
platform  |     return self._loop.run_until_complete(task)
platform  |            │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:80> wai...
platform  |            │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
platform  |            │    └ <uvloop.Loop running=True closed=False debug=False>
platform  |            └ <asyncio.runners.Runner object at 0x7fd605ee4d50>
platform  | > File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
platform  |     result = await app(  # type: ignore[func-returns-value]
platform  |                    └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fd5e9f29010>
platform  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
platform  |     return await self.app(scope, receive, send)
platform  |                  │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e936d7...
platform  |                  │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |                  │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |                  │    └ <fastapi.applications.FastAPI object at 0x7fd5ee6665d0>
platform  |                  └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fd5e9f29010>
platform  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
platform  |     await super().__call__(scope, receive, send)
platform  |                            │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e936d7...
platform  |                            │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |                            └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
platform  |     await self.middleware_stack(scope, receive, send)
platform  |           │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e936d7...
platform  |           │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |           │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fd5e9f2bfd0>
platform  |           └ <fastapi.applications.FastAPI object at 0x7fd5ee6665d0>
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
platform  |     raise exc
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
platform  |     await self.app(scope, receive, _send)
platform  |           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fd5e936a980>
platform  |           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |           │    └ <starlette.middleware.cors.CORSMiddleware object at 0x7fd5ee6467d0>
platform  |           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fd5e9f2bfd0>
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
platform  |     await self.simple_response(scope, receive, send, request_headers=headers)
platform  |           │    │               │      │        │                     └ Headers({'host': 'localhost:8000', 'connection': 'keep-alive', 'content-length': '654', 'cache-control': 'max-age=0', 'sec-ch...
platform  |           │    │               │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fd5e936a980>
platform  |           │    │               │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |           │    │               └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |           │    └ <function CORSMiddleware.simple_response at 0x7fd604e30ae0>
platform  |           └ <starlette.middleware.cors.CORSMiddleware object at 0x7fd5ee6467d0>
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
platform  |     await self.app(scope, receive, send)
platform  |           │    │   │      │        └ functools.partial(<bound method CORSMiddleware.send of <starlette.middleware.cors.CORSMiddleware object at 0x7fd5ee6467d0>>, ...
platform  |           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fd5e93...
platform  |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.24.0.4', 8000), 'c...
platform  |           │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fd5e9e34890>
platform  |           └ <starlette.middleware.cors.CORSMiddleware object at 0x7fd5ee6467d0>
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
platform  |     raise exc
platform  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
platform  |     await self.app(scope, receive, sender)
... (72 lines left)
```

### Steps to reproduce

It works on my end, this was reported by https://discord.com/channels/1094791204958392551/1094791206015348820/1113577062024884314

### Possible solution

It may have to do with SERP credits on the account, it may also have to do with the region you're calling SERP from 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AgentGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by PascalKrogt** [comment]
Adding the serper api key to the .env file at `REWORKD_PLATFORM_SERP_API_KEY=` solved this issue for me.

**Comment by wattyven** [comment]
> Adding the serper api key to the .env file at `REWORKD_PLATFORM_SERP_API_KEY=` solved this issue for me.
> 
> https://serper.dev/playground

Thanks for the fix, encountered this issue as well.

**Comment by jasangill1** [comment]
Problem solved!

**Comment by wattyven** [comment]
> Thanks @PascalKrogt and @wattyven! Seems like people are using the wrong Serper API key or something.

Initially, I tried using a SerpAPI key, which was the issue - when I realized I was supposed to use a Serper key, that fixed everything.
