### ISSUE TITLE
RangeError [ERR_HTTP_INVALLD_STATUS_CODE]:Invalid status code:0

### ISSUE THREAD

**Issue by lengmo714** [reworkd/AgentGPT#81]
error - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 0
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.writeHead (node:_http_server:344:11)
    at ServerResponse.writeHead (E:\otherfile\AgentGPT\node_modules\next\dist\compiled\compression\index.js:46:263)
    at ServerResponse._implicitHeader (node:_http_server:335:8)
    at ServerResponse.end (E:\otherfile\AgentGPT\node_modules\next\dist\compiled\compression\index.js:22:749)
    at DevServer.runEdgeFunction (E:\otherfile\AgentGPT\node_modules\next\dist\server\next-server.js:1461:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (E:\otherfile\AgentGPT\node_modules\next\dist\server\next-server.js:468:47)
    at async Object.fn (E:\otherfile\AgentGPT\node_modules\next\dist\server\next-server.js:751:37)
    at async Router.execute (E:\otherfile\AgentGPT\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (E:\otherfile\AgentGPT\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (E:\otherfile\AgentGPT\node_modules\next\dist\server\dev\next-dev-server.js:743:20)
    at async DevServer.handleRequest (E:\otherfile\AgentGPT\node_modules\next\dist\server\base-server.js:322:20) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'

**Comment by 18296070379** [comment]
Have you solved this problem，Can it be an agency issue?

**Comment by yourepicservices** [comment]
Similar to #90

**Comment by asim-shrestha** [comment]
Hey are you still experiencing this? @lengmo714  @18296070379

**Comment by asim-shrestha** [comment]
Closing due to duplication, appears to be fixed in #256

**Comment by lengmo714** [comment]
谢谢您的来信，稍会儿给您回信。

**Comment by asim-shrestha** [comment]
Ah apologies, I initially linked an incorrect issue earlier this appears to be linked to #90. Given the discussion there is bigger, lets move our discussion there
